In [2]:
import numpy as np

listA = [[2,-90,1],[3,-1,2],[4,0,6]]
A = np.array(listA)
print(A)

[[  2 -90   1]
 [  3  -1   2]
 [  4   0   6]]


In [3]:
invA = np.linalg.inv(A)
print(invA)

[[-0.00672646  0.60538117 -0.20067265]
 [-0.01121076  0.00896861 -0.00112108]
 [ 0.0044843  -0.40358744  0.30044843]]


In [9]:
Y= np.array([[10,-11,0],[4,9,-1],[3,-4,5]])
B = np.linalg.solve(A,Y)
print(B)


[[ 1.75224215  6.32511211 -1.60874439]
 [-0.07959641  0.20852018 -0.01457399]
 [-0.66816143 -4.88340807  1.9058296 ]]


In [10]:
C = np.transpose(B)
print(C)

[[ 1.75224215 -0.07959641 -0.66816143]
 [ 6.32511211  0.20852018 -4.88340807]
 [-1.60874439 -0.01457399  1.9058296 ]]


In [16]:
from numpy.linalg import eig
a,b = eig(C)
print(a,b)
#eigenvalues and eigenvectors of C

[2.67859984 0.8684873  0.31950478] [[-0.13609545 -0.399481    0.11196047]
 [-0.94382393  0.68441325  0.98612041]
 [ 0.30112194 -0.60991265  0.12260257]]
